-- ============================================================================
-- Migration: Add auth/admin support tables for Oracle runtime
-- Date: 2026-02-24
-- Purpose:
--   Adds MODULES, USER_MODULE_ACCESS, AUDIT_LOGS objects required by admin/
--   security APIs when upgrading existing Oracle deployments.
-- ============================================================================

-- 1) MODULES table
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'MODULES';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE modules (
                module_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                module_name VARCHAR2(100) UNIQUE NOT NULL,
                display_name VARCHAR2(200) NOT NULL,
                description VARCHAR2(1000),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )';
    END IF;
END;
/

-- 2) USER_MODULE_ACCESS table
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'USER_MODULE_ACCESS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE user_module_access (
                access_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                module_key VARCHAR2(100) NOT NULL,
                is_enabled NUMBER(1) DEFAULT 1 NOT NULL,
                assigned_by NUMBER,
                assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT uq_user_module_access UNIQUE (user_id, module_key),
                CONSTRAINT fk_user_module_access_user FOREIGN KEY (user_id) REFERENCES users(user_id),
                CONSTRAINT fk_user_module_access_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(user_id)
            )';
    END IF;
END;
/

-- 3) Index for USER_MODULE_ACCESS.USER_ID
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_USER_MODULE_ACCESS_USER';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_user_module_access_user ON user_module_access(user_id)';
    END IF;
END;
/

-- 4) AUDIT_LOGS table
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'AUDIT_LOGS';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE audit_logs (
                log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER,
                action VARCHAR2(100) NOT NULL,
                resource_type VARCHAR2(100),
                resource_id VARCHAR2(100),
                ip_address VARCHAR2(45),
                user_agent VARCHAR2(1000),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(user_id)
            )';
    END IF;
END;
/

-- 5) Index for AUDIT_LOGS.CREATED_AT
DECLARE
    v_count NUMBER := 0;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_indexes
    WHERE index_name = 'IDX_AUDIT_LOGS_CREATED_AT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX idx_audit_logs_created_at ON audit_logs(created_at)';
    END IF;
END;
/

-- 6) Seed default modules (idempotent)
MERGE INTO modules target
USING (
    SELECT 'dashboard' module_name, 'Dashboard' display_name, 'Main dashboard features' description FROM dual
    UNION ALL SELECT 'users', 'Users Management', 'User management features' FROM dual
    UNION ALL SELECT 'reports', 'Reports', 'Reporting features' FROM dual
    UNION ALL SELECT 'analytics', 'Analytics', 'Analytics features' FROM dual
    UNION ALL SELECT 'settings', 'Settings', 'System settings' FROM dual
) src
ON (target.module_name = src.module_name)
WHEN NOT MATCHED THEN
    INSERT (module_name, display_name, description)
    VALUES (src.module_name, src.display_name, src.description);

COMMIT;
