-- ============================================================================
-- DASHBOARD CREATOR PHASE 1 MIGRATION (POSTGRESQL)
-- ============================================================================
-- Date: 2026-02-20
-- Purpose:
--   Create metadata tables required for Dashboard Creator foundation.
--
-- Critical naming convention:
--   This script intentionally uses lower-case table names and lower-case
--   column names to align with existing PostgreSQL metadata standards.
-- ============================================================================

begin;

-- ---------------------------------------------------------------------------
-- 1) dashboard definition table
-- ---------------------------------------------------------------------------
create table if not exists dms_dash_def (
    dashid            bigint generated by default as identity primary key,
    dashnm            varchar(200) not null,
    dscrptn           varchar(1000),
    owner_usrid       bigint,
    is_actv           char(1) not null default 'Y',
    curflg            char(1) not null default 'Y',
    crtdby            varchar(100),
    crtddt            timestamp not null default current_timestamp,
    updtdby           varchar(100),
    updtdt            timestamp
);

create unique index if not exists uk_dms_dash_def_nm_owner
    on dms_dash_def (dashnm, owner_usrid, curflg);

create index if not exists idx_dms_dash_def_owner
    on dms_dash_def (owner_usrid, is_actv, curflg);

comment on table dms_dash_def is 'dashboard creator header metadata';
comment on column dms_dash_def.dashid is 'primary key';
comment on column dms_dash_def.dashnm is 'dashboard name';
comment on column dms_dash_def.owner_usrid is 'owner user id from users table';

-- ---------------------------------------------------------------------------
-- 2) dashboard widget table
-- ---------------------------------------------------------------------------
create table if not exists dms_dash_widget (
    widgtid           bigint generated by default as identity primary key,
    dashid            bigint not null,
    widgtnm           varchar(200) not null,
    widgttyp          varchar(30) not null,
    srcmode           varchar(20) not null,
    sqlsrcid          bigint,
    adhcsql           text,
    dbcnid            bigint,
    cfg_json          text,
    layout_json       text,
    order_no          integer default 1,
    is_actv           char(1) not null default 'Y',
    curflg            char(1) not null default 'Y',
    crtdby            varchar(100),
    crtddt            timestamp not null default current_timestamp,
    updtdby           varchar(100),
    updtdt            timestamp,
    constraint fk_dash_widget_def foreign key (dashid) references dms_dash_def(dashid)
);

create index if not exists idx_dms_dash_widget_dash
    on dms_dash_widget (dashid, is_actv, curflg, order_no);

comment on table dms_dash_widget is 'dashboard widgets and chart config metadata';
comment on column dms_dash_widget.srcmode is 'table/sql/report_ref';
comment on column dms_dash_widget.cfg_json is 'widget field mapping and chart config';

-- ---------------------------------------------------------------------------
-- 3) dashboard filter table
-- ---------------------------------------------------------------------------
create table if not exists dms_dash_filter (
    fltrid            bigint generated by default as identity primary key,
    dashid            bigint not null,
    scope_typ         varchar(20) not null,
    widgtid           bigint,
    fltr_key          varchar(100) not null,
    fltr_typ          varchar(30) not null,
    fltr_cfg_json     text,
    is_actv           char(1) not null default 'Y',
    curflg            char(1) not null default 'Y',
    crtdby            varchar(100),
    crtddt            timestamp not null default current_timestamp,
    updtdby           varchar(100),
    updtdt            timestamp,
    constraint fk_dash_filter_def foreign key (dashid) references dms_dash_def(dashid),
    constraint fk_dash_filter_widget foreign key (widgtid) references dms_dash_widget(widgtid)
);

create index if not exists idx_dms_dash_filter_dash
    on dms_dash_filter (dashid, is_actv, curflg);

comment on table dms_dash_filter is 'global and widget-level filters for dashboards';

-- ---------------------------------------------------------------------------
-- 4) dashboard sharing table
-- ---------------------------------------------------------------------------
create table if not exists dms_dash_share (
    shareid           bigint generated by default as identity primary key,
    dashid            bigint not null,
    share_typ         varchar(20) not null,
    share_ref_id      bigint not null,
    can_view          char(1) not null default 'Y',
    can_edit          char(1) not null default 'N',
    can_export        char(1) not null default 'Y',
    is_actv           char(1) not null default 'Y',
    curflg            char(1) not null default 'Y',
    crtdby            varchar(100),
    crtddt            timestamp not null default current_timestamp,
    updtdby           varchar(100),
    updtdt            timestamp,
    constraint fk_dash_share_def foreign key (dashid) references dms_dash_def(dashid)
);

create unique index if not exists uk_dms_dash_share_uk
    on dms_dash_share (dashid, share_typ, share_ref_id, curflg);

comment on table dms_dash_share is 'share settings by user or role for dashboards';
comment on column dms_dash_share.share_typ is 'user/role';

-- ---------------------------------------------------------------------------
-- 5) dashboard export log table
-- ---------------------------------------------------------------------------
create table if not exists dms_dash_export_log (
    expid             bigint generated by default as identity primary key,
    dashid            bigint not null,
    exprt_fmt         varchar(10) not null,
    exprt_by          varchar(100),
    exprt_at          timestamp not null default current_timestamp,
    stts              varchar(20) default 'SUCCESS',
    msg               varchar(2000),
    file_nm           varchar(500),
    file_sz_bytes     bigint,
    constraint fk_dash_export_def foreign key (dashid) references dms_dash_def(dashid)
);

create index if not exists idx_dms_dash_export_dash
    on dms_dash_export_log (dashid, exprt_at);

comment on table dms_dash_export_log is 'audit trail for dashboard pdf/ppt exports';

commit;

-- ---------------------------------------------------------------------------
-- verification queries
-- ---------------------------------------------------------------------------
-- select table_name
-- from information_schema.tables
-- where table_name in (
--   'dms_dash_def','dms_dash_widget','dms_dash_filter','dms_dash_share','dms_dash_export_log'
-- )
-- order by table_name;

-- ---------------------------------------------------------------------------
-- rollback (manual)
-- ---------------------------------------------------------------------------
-- drop table if exists dms_dash_export_log;
-- drop table if exists dms_dash_share;
-- drop table if exists dms_dash_filter;
-- drop table if exists dms_dash_widget;
-- drop table if exists dms_dash_def;

-- ============================================================================
-- end of postgresql migration
-- ============================================================================
