-- ============================================================================
-- DMS Full Metadata Install Script (PostgreSQL)
-- Date: 2026-02-24
-- Purpose: Fresh install of metadata objects required by the application.
-- ============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    salt VARCHAR(255) NOT NULL,
    is_active SMALLINT DEFAULT 0,
    account_status VARCHAR(50) DEFAULT 'PENDING',
    created_by BIGINT,
    approved_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP,
    password_reset_token VARCHAR(255),
    password_reset_expires TIMESTAMP,
    failed_login_attempts INTEGER DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);

CREATE TABLE IF NOT EXISTS user_profiles (
    profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT UNIQUE NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    phone_number VARCHAR(20),
    department VARCHAR(100),
    position VARCHAR(100),
    profile_image_path VARCHAR(500),
    CONSTRAINT fk_user_profiles_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS roles (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name VARCHAR(100) UNIQUE NOT NULL,
    description VARCHAR(500),
    is_system_role SMALLINT DEFAULT 0
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_by BIGINT NOT NULL,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id) REFERENCES roles(role_id),
    CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS permission_matrix (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    module_name VARCHAR(100) NOT NULL,
    can_view SMALLINT DEFAULT 0,
    can_create SMALLINT DEFAULT 0,
    can_edit SMALLINT DEFAULT 0,
    can_delete SMALLINT DEFAULT 0,
    CONSTRAINT uq_role_module UNIQUE (role_id, module_name),
    CONSTRAINT fk_permission_matrix_role FOREIGN KEY (role_id) REFERENCES roles(role_id)
);

CREATE TABLE IF NOT EXISTS password_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_password_history_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS login_audit_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    target_user_id BIGINT,
    login_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ip_address VARCHAR(45) NOT NULL,
    login_status VARCHAR(20) NOT NULL,
    login_type VARCHAR(20) NOT NULL,
    details TEXT,
    CONSTRAINT fk_login_audit_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_login_audit_target_user FOREIGN KEY (target_user_id) REFERENCES users(user_id)
);

CREATE TABLE IF NOT EXISTS modules (
    module_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_name VARCHAR(100) UNIQUE NOT NULL,
    display_name VARCHAR(200) NOT NULL,
    description VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_module_access (
    access_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    module_key VARCHAR(100) NOT NULL,
    is_enabled SMALLINT DEFAULT 1 NOT NULL,
    assigned_by BIGINT,
    assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_user_module_access UNIQUE (user_id, module_key),
    CONSTRAINT fk_user_module_access_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT fk_user_module_access_assigned_by FOREIGN KEY (assigned_by) REFERENCES users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_user_module_access_user ON user_module_access(user_id);

CREATE TABLE IF NOT EXISTS audit_logs (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    action VARCHAR(100) NOT NULL,
    resource_type VARCHAR(100),
    resource_id VARCHAR(100),
    ip_address VARCHAR(45),
    user_agent VARCHAR(1000),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user FOREIGN KEY (user_id) REFERENCES users(user_id)
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs(created_at);

INSERT INTO modules (module_name, display_name, description)
VALUES
    ('dashboard', 'Dashboard', 'Main dashboard features'),
    ('users', 'Users Management', 'User management features'),
    ('reports', 'Reports', 'Reporting features'),
    ('analytics', 'Analytics', 'Analytics features'),
    ('settings', 'Settings', 'System settings')
ON CONFLICT (module_name) DO NOTHING;

CREATE TABLE IF NOT EXISTS dms_dbcondtls (
    conid BIGINT PRIMARY KEY,
    connm VARCHAR(100),
    dbhost VARCHAR(100),
    dbport INTEGER,
    dbsrvnm VARCHAR(100),
    usrnm VARCHAR(100),
    passwd VARCHAR(400),
    constr VARCHAR(1000),
    schnm VARCHAR(128) NOT NULL,
    curflg CHAR(1) DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS dms_params (
    prtyp VARCHAR(100) NOT NULL,
    prcd VARCHAR(100) NOT NULL,
    prdesc VARCHAR(500),
    prval VARCHAR(4000),
    dbtyp VARCHAR(50) DEFAULT 'GENERIC',
    prreccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    prrecupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y',
    CONSTRAINT uk_dms_params_type_db_code UNIQUE (prtyp, dbtyp, prcd)
);
CREATE INDEX IF NOT EXISTS idx_dms_params_datatype_db ON dms_params(prtyp, dbtyp, prcd);

CREATE TABLE IF NOT EXISTS dms_supported_databases (
    dbid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dbtyp VARCHAR(50) UNIQUE NOT NULL,
    dbdesc VARCHAR(200),
    dbvrsn VARCHAR(50),
    status VARCHAR(20) DEFAULT 'ACTIVE',
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updtdby VARCHAR(100),
    updtdt TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dms_supported_db_status ON dms_supported_databases(status, dbtyp);

CREATE TABLE IF NOT EXISTS dms_maprsql (
    maprsqlid BIGINT PRIMARY KEY,
    maprsqlcd VARCHAR(100) NOT NULL,
    maprsql TEXT,
    sqlconid BIGINT,
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y',
    CONSTRAINT fk_dms_maprsql_sqlconid FOREIGN KEY (sqlconid) REFERENCES dms_dbcondtls(conid)
);
CREATE INDEX IF NOT EXISTS idx_dms_maprsql_cd_cur ON dms_maprsql(maprsqlcd, curflg);

CREATE TABLE IF NOT EXISTS dms_mapr (
    mapid BIGINT PRIMARY KEY,
    mapref VARCHAR(50) UNIQUE NOT NULL,
    mapdesc VARCHAR(500),
    trgschm VARCHAR(100),
    trgtbtyp VARCHAR(20),
    trgtbnm VARCHAR(100),
    frqcd VARCHAR(10),
    srcsystm VARCHAR(100),
    lgvrfyflg CHAR(1) DEFAULT 'N',
    lgvrfydt TIMESTAMP,
    stflg CHAR(1) DEFAULT 'N',
    blkprcrows INTEGER,
    trgconid BIGINT,
    chkpntstrtgy VARCHAR(20) DEFAULT 'AUTO',
    chkpntclnm VARCHAR(100),
    chkpntenbld CHAR(1) DEFAULT 'Y',
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y',
    crtdby VARCHAR(100),
    uptdby VARCHAR(100),
    CONSTRAINT fk_dms_mapr_trgconid FOREIGN KEY (trgconid) REFERENCES dms_dbcondtls(conid)
);
CREATE INDEX IF NOT EXISTS idx_dms_mapr_ref_cur ON dms_mapr(mapref, curflg);

CREATE TABLE IF NOT EXISTS dms_maprdtl (
    mapdtlid BIGINT PRIMARY KEY,
    mapref VARCHAR(50) NOT NULL,
    trgclnm VARCHAR(100) NOT NULL,
    trgcldtyp VARCHAR(50),
    trgkeyflg CHAR(1),
    trgkeyseq INTEGER,
    trgcldesc VARCHAR(500),
    maplogic TEXT,
    maprsqlcd VARCHAR(100),
    keyclnm VARCHAR(100),
    valclnm VARCHAR(100),
    mapcmbcd VARCHAR(20),
    excseq INTEGER,
    scdtyp INTEGER,
    lgvrfyflg CHAR(1),
    lgvrfydt TIMESTAMP,
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y',
    crtdby VARCHAR(100),
    uptdby VARCHAR(100),
    CONSTRAINT fk_dms_maprdtl_mapref FOREIGN KEY (mapref) REFERENCES dms_mapr(mapref)
);
CREATE INDEX IF NOT EXISTS idx_dms_maprdtl_ref_cur ON dms_maprdtl(mapref, curflg);

CREATE TABLE IF NOT EXISTS dms_maperr (
    maperrid BIGINT PRIMARY KEY,
    mapdtlid BIGINT,
    mapref VARCHAR(50),
    maplogic TEXT,
    errtyp VARCHAR(20),
    errmsg TEXT,
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dms_job (
    jobid BIGINT PRIMARY KEY,
    mapid BIGINT,
    mapref VARCHAR(50) NOT NULL,
    frqcd VARCHAR(10),
    trgschm VARCHAR(100),
    trgtbtyp VARCHAR(20),
    trgtbnm VARCHAR(100),
    srcsystm VARCHAR(100),
    stflg CHAR(1),
    blkprcrows INTEGER,
    trgconid BIGINT,
    chkpntstrtgy VARCHAR(20),
    chkpntclnm VARCHAR(100),
    chkpntenbld CHAR(1),
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS dms_jobdtl (
    jobdtlid BIGINT PRIMARY KEY,
    mapref VARCHAR(50) NOT NULL,
    mapdtlid BIGINT,
    trgclnm VARCHAR(100),
    trgcldtyp VARCHAR(50),
    trgkeyflg CHAR(1),
    trgkeyseq INTEGER,
    trgcldesc VARCHAR(500),
    maplogic TEXT,
    maprsqlcd VARCHAR(100),
    keyclnm VARCHAR(100),
    valclnm VARCHAR(100),
    mapcmbcd VARCHAR(20),
    excseq INTEGER,
    scdtyp INTEGER,
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS dms_jobflw (
    jobflwid BIGINT PRIMARY KEY,
    jobid BIGINT,
    mapref VARCHAR(50),
    trgschm VARCHAR(100),
    trgtbtyp VARCHAR(20),
    trgtbnm VARCHAR(100),
    dwlogic TEXT,
    stflg CHAR(1) DEFAULT 'A',
    recrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y'
);

CREATE TABLE IF NOT EXISTS dms_jobsch (
    jobschid BIGINT PRIMARY KEY,
    jobid BIGINT NOT NULL,
    mapref VARCHAR(50) NOT NULL,
    frqcd VARCHAR(10),
    frqdd VARCHAR(10),
    frqhh INTEGER,
    frqmi INTEGER,
    enableflg CHAR(1) DEFAULT 'Y',
    dpnd_jobschid BIGINT,
    strdt TIMESTAMP,
    enddt TIMESTAMP,
    lst_run_dt TIMESTAMP,
    nxt_run_dt TIMESTAMP,
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y',
    CONSTRAINT fk_dms_jobsch_job FOREIGN KEY (jobid) REFERENCES dms_job(jobid)
);

CREATE TABLE IF NOT EXISTS dms_prclog (
    prcid BIGINT PRIMARY KEY,
    jobid BIGINT,
    jobflwid BIGINT,
    strtdt TIMESTAMP,
    enddt TIMESTAMP,
    status VARCHAR(10),
    msg TEXT,
    prclog TEXT,
    mapref VARCHAR(100),
    sessionid NUMERIC(30,0),
    param1 VARCHAR(4000), param2 VARCHAR(4000), param3 VARCHAR(4000), param4 VARCHAR(4000), param5 VARCHAR(4000),
    param6 VARCHAR(4000), param7 VARCHAR(4000), param8 VARCHAR(4000), param9 VARCHAR(4000), param10 VARCHAR(4000),
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    recupdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dms_joblog (
    joblogid BIGINT PRIMARY KEY,
    prcdt TIMESTAMP,
    mapref VARCHAR(100),
    jobid BIGINT,
    srcrows BIGINT,
    trgrows BIGINT,
    errrows BIGINT,
    prcid BIGINT,
    sessionid NUMERIC(30,0),
    reccrdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dms_joberr (
    joblogid BIGINT,
    errid BIGINT,
    prcdt TIMESTAMP,
    errtyp VARCHAR(10),
    dberrmsg TEXT,
    errmsg TEXT,
    keyvalue VARCHAR(1000),
    jobid BIGINT,
    sessionid NUMERIC(30,0),
    prcid BIGINT,
    mapref VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS dms_prcreq (
    request_id VARCHAR(64) PRIMARY KEY,
    mapref VARCHAR(100) NOT NULL,
    request_type VARCHAR(30) NOT NULL,
    payload TEXT,
    status VARCHAR(20) DEFAULT 'NEW',
    requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    claimed_at TIMESTAMP,
    claimed_by VARCHAR(64),
    completed_at TIMESTAMP,
    result_payload TEXT
);
CREATE INDEX IF NOT EXISTS dms_prcreq_status_idx ON dms_prcreq(status, requested_at);
CREATE INDEX IF NOT EXISTS dms_prcreq_mapref_idx ON dms_prcreq(mapref);

CREATE TABLE IF NOT EXISTS dms_idpool (
    entity_name VARCHAR(64) PRIMARY KEY,
    current_value BIGINT NOT NULL,
    block_size INTEGER DEFAULT 500,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_dms_idpool_updated ON dms_idpool(updated_at);

CREATE TABLE IF NOT EXISTS dms_flupld (
    flupldid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flupldref VARCHAR(100) UNIQUE NOT NULL,
    fluplddesc VARCHAR(500),
    flnm VARCHAR(255),
    flpth VARCHAR(2000),
    fltyp VARCHAR(50),
    trgconid BIGINT,
    trgschm VARCHAR(100),
    trgtblnm VARCHAR(100),
    trnctflg CHAR(1) DEFAULT 'N',
    hdrrwcnt INTEGER DEFAULT 0,
    ftrrwcnt INTEGER DEFAULT 0,
    hdrrwpttrn VARCHAR(500),
    ftrrwpttrn VARCHAR(500),
    frqcd VARCHAR(10),
    stflg CHAR(1) DEFAULT 'N',
    curflg CHAR(1) DEFAULT 'Y',
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uptdby VARCHAR(100),
    uptdt TIMESTAMP,
    lstrundt TIMESTAMP,
    nxtrundt TIMESTAMP,
    batch_size INTEGER DEFAULT 1000,
    flhash VARCHAR(64), flsz BIGINT, flmimtyp VARCHAR(100),
    flvrfyflg CHAR(1) DEFAULT 'N', flvrfydt TIMESTAMP, flvrfyby VARCHAR(100),
    flqrnflg CHAR(1) DEFAULT 'N', flqrnrsn VARCHAR(500),
    flscnflg CHAR(1) DEFAULT 'N', flscndt TIMESTAMP, flscnrslt VARCHAR(50),
    flacclvl VARCHAR(20) DEFAULT 'PRIVATE',
    flencflg CHAR(1) DEFAULT 'N', flencalg VARCHAR(50),
    flupldcnt INTEGER DEFAULT 0, fllstacctm TIMESTAMP, flacccnt INTEGER DEFAULT 0,
    flrtrntm TIMESTAMP, flrtrnplcy VARCHAR(50)
);
CREATE INDEX IF NOT EXISTS idx_flupld_ref ON dms_flupld(flupldref);
CREATE INDEX IF NOT EXISTS idx_flupld_trgconid ON dms_flupld(trgconid);
CREATE INDEX IF NOT EXISTS idx_flupld_curflg ON dms_flupld(curflg);

CREATE TABLE IF NOT EXISTS dms_fluplddtl (
    fluplddtlid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flupldref VARCHAR(100) NOT NULL,
    srcclnm VARCHAR(100),
    trgclnm VARCHAR(100) NOT NULL,
    trgcldtyp VARCHAR(50),
    trgkyflg CHAR(1) DEFAULT 'N',
    trgkyseq INTEGER,
    trgcldesc VARCHAR(500),
    drvlgc TEXT,
    drvlgcflg CHAR(1) DEFAULT 'N',
    excseq INTEGER,
    isaudit CHAR(1) DEFAULT 'N',
    audttyp VARCHAR(20),
    dfltval VARCHAR(500),
    isrqrd CHAR(1) DEFAULT 'N',
    curflg CHAR(1) DEFAULT 'Y',
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uptdby VARCHAR(100),
    uptdt TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_fluplddtl_ref ON dms_fluplddtl(flupldref);
CREATE INDEX IF NOT EXISTS idx_fluplddtl_curflg ON dms_fluplddtl(curflg);

CREATE TABLE IF NOT EXISTS dms_flupldacclg (
    acclgid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flupldref VARCHAR(100) NOT NULL,
    usrid INTEGER,
    usrnm VARCHAR(100),
    acctyp VARCHAR(20),
    accdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ipaddr VARCHAR(45),
    usragnt VARCHAR(500),
    accsts VARCHAR(20),
    accrsn VARCHAR(500),
    flsz BIGINT,
    flhash VARCHAR(64)
);
CREATE INDEX IF NOT EXISTS idx_flupldacclg_ref ON dms_flupldacclg(flupldref);
CREATE INDEX IF NOT EXISTS idx_flupldacclg_usrid ON dms_flupldacclg(usrid);
CREATE INDEX IF NOT EXISTS idx_flupldacclg_accdt ON dms_flupldacclg(accdt);
CREATE INDEX IF NOT EXISTS idx_flupldacclg_acctyp ON dms_flupldacclg(acctyp);

CREATE TABLE IF NOT EXISTS dms_flupldvld (
    vldid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fltyp VARCHAR(50) NOT NULL,
    maxsz BIGINT,
    alwdexns TEXT,
    alwdmimtyps TEXT,
    blckdexns TEXT,
    blckdpttrns TEXT,
    rqrvrfy CHAR(1) DEFAULT 'Y',
    rqrscn CHAR(1) DEFAULT 'Y',
    rqrenc CHAR(1) DEFAULT 'N',
    maxclmcnt INTEGER,
    maxrwcnt BIGINT,
    vldcntnt CHAR(1) DEFAULT 'Y',
    curflg CHAR(1) DEFAULT 'Y',
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uptdby VARCHAR(100),
    uptdt TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_flupldvld_fltyp ON dms_flupldvld(fltyp);

CREATE TABLE IF NOT EXISTS dms_flupldsec (
    secid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scnngnbl CHAR(1) DEFAULT 'Y',
    scnngprvd VARCHAR(50),
    scnngcmd VARCHAR(500),
    rqrvrfy CHAR(1) DEFAULT 'Y',
    rqrenc CHAR(1) DEFAULT 'N',
    encalg VARCHAR(50),
    qrntnflg CHAR(1) DEFAULT 'Y',
    qrntndir VARCHAR(1000),
    rtrntm INTEGER DEFAULT 90,
    maxflsz BIGINT DEFAULT 104857600,
    maxupldhr INTEGER DEFAULT 50,
    maxszhr BIGINT DEFAULT 524288000,
    alwdflexts TEXT,
    blckdflexts TEXT,
    alwdiprngs TEXT,
    blckdiprngs TEXT,
    curflg CHAR(1) DEFAULT 'Y',
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uptdby VARCHAR(100),
    uptdt TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dms_flupld_schd (
    schdid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flupldref VARCHAR(50) NOT NULL,
    frqncy VARCHAR(10) NOT NULL,
    tm_prm VARCHAR(100),
    nxt_run_dt TIMESTAMP,
    lst_run_dt TIMESTAMP,
    stts VARCHAR(20) NOT NULL,
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uptdby VARCHAR(100),
    uptdt TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y'
);
CREATE INDEX IF NOT EXISTS idx_flupld_schd_flupldref ON dms_flupld_schd(flupldref);
CREATE INDEX IF NOT EXISTS idx_flupld_schd_frqncy ON dms_flupld_schd(frqncy);
CREATE INDEX IF NOT EXISTS idx_flupld_schd_nxtrun ON dms_flupld_schd(nxt_run_dt);

CREATE TABLE IF NOT EXISTS dms_flupld_run (
    runid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flupldref VARCHAR(50) NOT NULL,
    strttm TIMESTAMP NOT NULL,
    ndtm TIMESTAMP,
    rwsprcssd INTEGER DEFAULT 0,
    rwsstccssfl INTEGER DEFAULT 0,
    rwsfld INTEGER DEFAULT 0,
    stts VARCHAR(20) NOT NULL,
    mssg TEXT,
    ldmde VARCHAR(20),
    flpth TEXT,
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    uptdby VARCHAR(100),
    uptdt TIMESTAMP,
    curflg CHAR(1) DEFAULT 'Y'
);
CREATE INDEX IF NOT EXISTS idx_flupld_run_flupldref ON dms_flupld_run(flupldref);
CREATE INDEX IF NOT EXISTS idx_flupld_run_start_time ON dms_flupld_run(strttm DESC);

CREATE TABLE IF NOT EXISTS dms_flupld_err (
    errid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flupldref VARCHAR(50) NOT NULL,
    runid BIGINT NOT NULL,
    rwndx INTEGER NOT NULL,
    rwdtjsn JSONB,
    rrcd VARCHAR(50),
    rrmssg TEXT NOT NULL,
    crtdby VARCHAR(100),
    crtdt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_flupld_err_flupldref ON dms_flupld_err(flupldref);
CREATE INDEX IF NOT EXISTS idx_flupld_err_runid ON dms_flupld_err(runid);
CREATE INDEX IF NOT EXISTS idx_flupld_err_rrcd ON dms_flupld_err(rrcd);

CREATE TABLE IF NOT EXISTS dms_dash_def (
    dashid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashnm VARCHAR(200) NOT NULL,
    dscrptn VARCHAR(1000),
    owner_usrid BIGINT,
    is_actv CHAR(1) DEFAULT 'Y' NOT NULL,
    curflg CHAR(1) DEFAULT 'Y' NOT NULL,
    crtdby VARCHAR(100),
    crtddt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updtdby VARCHAR(100),
    updtdt TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_dms_dash_def_nm_owner ON dms_dash_def(dashnm, owner_usrid, curflg);
CREATE INDEX IF NOT EXISTS idx_dms_dash_def_owner ON dms_dash_def(owner_usrid, is_actv, curflg);

CREATE TABLE IF NOT EXISTS dms_dash_widget (
    widgtid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashid BIGINT NOT NULL,
    widgtnm VARCHAR(200) NOT NULL,
    widgttyp VARCHAR(30) NOT NULL,
    srcmode VARCHAR(20) NOT NULL,
    sqlsrcid BIGINT,
    adhcsql TEXT,
    dbcnid BIGINT,
    cfg_json TEXT,
    layout_json TEXT,
    order_no INTEGER DEFAULT 1,
    is_actv CHAR(1) DEFAULT 'Y' NOT NULL,
    curflg CHAR(1) DEFAULT 'Y' NOT NULL,
    crtdby VARCHAR(100),
    crtddt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updtdby VARCHAR(100),
    updtdt TIMESTAMP,
    CONSTRAINT fk_dash_widget_def FOREIGN KEY (dashid) REFERENCES dms_dash_def(dashid)
);
CREATE INDEX IF NOT EXISTS idx_dms_dash_widget_dash ON dms_dash_widget(dashid, is_actv, curflg, order_no);

CREATE TABLE IF NOT EXISTS dms_dash_filter (
    fltrid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashid BIGINT NOT NULL,
    scope_typ VARCHAR(20) NOT NULL,
    widgtid BIGINT,
    fltr_key VARCHAR(100) NOT NULL,
    fltr_typ VARCHAR(30) NOT NULL,
    fltr_cfg_json TEXT,
    is_actv CHAR(1) DEFAULT 'Y' NOT NULL,
    curflg CHAR(1) DEFAULT 'Y' NOT NULL,
    crtdby VARCHAR(100),
    crtddt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updtdby VARCHAR(100),
    updtdt TIMESTAMP,
    CONSTRAINT fk_dash_filter_def FOREIGN KEY (dashid) REFERENCES dms_dash_def(dashid),
    CONSTRAINT fk_dash_filter_widget FOREIGN KEY (widgtid) REFERENCES dms_dash_widget(widgtid)
);
CREATE INDEX IF NOT EXISTS idx_dms_dash_filter_dash ON dms_dash_filter(dashid, is_actv, curflg);

CREATE TABLE IF NOT EXISTS dms_dash_share (
    shareid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashid BIGINT NOT NULL,
    share_typ VARCHAR(20) NOT NULL,
    share_ref_id BIGINT NOT NULL,
    can_view CHAR(1) DEFAULT 'Y' NOT NULL,
    can_edit CHAR(1) DEFAULT 'N' NOT NULL,
    can_export CHAR(1) DEFAULT 'Y' NOT NULL,
    is_actv CHAR(1) DEFAULT 'Y' NOT NULL,
    curflg CHAR(1) DEFAULT 'Y' NOT NULL,
    crtdby VARCHAR(100),
    crtddt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updtdby VARCHAR(100),
    updtdt TIMESTAMP,
    CONSTRAINT fk_dash_share_def FOREIGN KEY (dashid) REFERENCES dms_dash_def(dashid)
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_dms_dash_share_uk ON dms_dash_share(dashid, share_typ, share_ref_id, curflg);

CREATE TABLE IF NOT EXISTS dms_dash_export_log (
    expid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dashid BIGINT NOT NULL,
    exprt_fmt VARCHAR(10) NOT NULL,
    exprt_by VARCHAR(100),
    exprt_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    stts VARCHAR(20) DEFAULT 'SUCCESS',
    msg VARCHAR(2000),
    file_nm VARCHAR(500),
    file_sz_bytes BIGINT,
    CONSTRAINT fk_dash_export_def FOREIGN KEY (dashid) REFERENCES dms_dash_def(dashid)
);
CREATE INDEX IF NOT EXISTS idx_dms_dash_export_dash ON dms_dash_export_log(dashid, exprt_at);

CREATE SEQUENCE IF NOT EXISTS dms_maprsqlseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_maprseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_maprdtlseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_maperrseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_jobseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_jobdtlseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_jobflwseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_jobschseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_prclogseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_joblogseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_joberrseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_flupldseq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS dms_fluplddtlseq START WITH 1 INCREMENT BY 1;

INSERT INTO dms_supported_databases (dbtyp, dbdesc, dbvrsn, status, crtdby)
SELECT 'GENERIC', 'Generic/Universal Datatypes (Reference)', NULL, 'ACTIVE', 'SYSTEM'
WHERE NOT EXISTS (SELECT 1 FROM dms_supported_databases WHERE dbtyp = 'GENERIC');

UPDATE dms_params
SET dbtyp = 'GENERIC'
WHERE prtyp = 'Datatype' AND dbtyp IS NULL;

-- ============================================================================
-- Test Data Load Placeholder
-- Paste INSERT statements for your test data below and keep them in one transaction.
-- ============================================================================
-- BEGIN;
-- INSERT INTO dms_params (...);
-- INSERT INTO dms_mapr (...);
-- COMMIT;

COMMIT;
